word = ARGV[0].split('') #SPLIT PERMET DE CONVERTIR UN MOT EN UN TABLEAU.
i = 0  #i TRAVERSERA LE MOT INPUT ET DIRA QUEL LETTRE METTRE EN MAJ OU EN MINISCULE

while i < word.length #TANT QUE i N'A PAS TRAVERSÉ WORD JUSQU'AU BOUT, IL ITÉRERA
  if i % 2 == 0
    print word[i].upcase
  else
    print word[i].downcase
  end
  i += 1 #i PRENDRA TOUJOURS 1 POUR QUE MODULO FASSE UN RÉSULTAT DE 1 OU 0 POUR LES MAJ ET MIN
end

 print "\n" #PERMET DE NE PAS AVOIR DE % À LA FIN DU RÉSULTAT SANS DEVOIR METTRE PUTS
